version: 0.2

phases:
  install:
    commands:
      - echo Obtaining AWS Account ID and Region...
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - AWS_REGION=$(aws configure get region)
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
  pre_build:
    commands:
      - echo Cloning the GitHub repo...
      - git clone https://github.com/tmaior/anothersidetours-backend.git
      - cd anothersidetours-backend
      - echo Build Docker image...
      - docker build -t ECR_REPOSITORY_NAME .
      - echo Tagging Docker image...
      - docker tag ECR_REPOSITORY_NAME:latest account-id.dkr.ecr.AWS_REGION.amazonaws.com/ECR_REPOSITORY_NAME:latest
  build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push account-id.dkr.ecr.AWS_REGION.amazonaws.com/ECR_REPOSITORY_NAME:latest
  post_build:
    commands:
      - echo Updating ECS task definition and service...
      - task_id=$(aws ecs list-tasks --cluster ECS_CLUSTER_NAME --service-name SERVICE_NAME --query "taskArns[0]" --output text)
      - aws ecs stop-task --cluster ECS_CLUSTER_NAME --task $task_id
      - aws ecs update-service --cluster ECS_CLUSTER_NAME --service SERVICE_NAME --force-new-deployment
